### ISSUE TITLE
Configure the Sirius Interpreter view to work w/ OML models.

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml#105]
It seems that the Sirius Interpreter should enable users to write AQL queries to be evaluated over OML elements.

**Comment by dyates** [comment]
This is available via the Interpreter view (Acceleo Model to Text -> Interpreter).  Acceleo queries may be performed on model elements.  Documentation [here](https://wiki.eclipse.org/Acceleo/Interpreter#Expression) and [here](https://www.eclipse.org/sirius/doc/specifier/general/Writing_Queries.html#acceleo)

**Comment by NicolasRouquette** [comment]
Please describe an example of using the interpreter in the viewpoint's README.md and include these links as well.
