### ISSUE TITLE
Configure tycho for publishing.

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml#6]
Decide where to publish:
- open source (bintray?)
- internal builds (artifactory?)

Update tycho accordingly.

Note that publishing artifacts on bintray involves a 250Mb limit per artifact.

**Comment by sjiherzig** [comment]
There's a possibility to publish the update site directly on GitHub.com as well. See, e.g.: http://stackoverflow.com/questions/25238298/how-to-distribute-eclipse-update-site

**Comment by NicolasRouquette** [comment]
Resolved in https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/releases/tag/0.8.0.1
