### ISSUE TITLE
"The Value [X] is Invalid" Error When Parsing PositiveIntegerLiterals

### ISSUE THREAD

**Issue by sjiherzig** [JPL-IMCE/gov.nasa.jpl.imce.oml#89]
After changing from `INT` to `PositiveIntegerLiteral`, the `maxLength` and `minLength` properties fail to parse correctly.

Example (from the xsd.oml):

```oml
@dc:source="http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#integer"
@oml:JavaDatatypeBinding="java.math.BigInteger"
stringScalarRestriction XSDinteger {
	maxLength 10    // "The value 10 is invalid" error
	pattern /[\\\\-+]?[0-9]+/
	restrictedRange XSDdecimal
}
```

As illustrated, the error "The value 10 is invalid" is thrown in the IDE. Judging by the grammar, the above format _should_ be correct. From what I can tell, `maxLength` is parsed as a `PositiveIntegerLiteral`, which is defined in the following way:

```xtext
PositiveIntegerLiteral returns PositiveIntegerLiteral: 	DIGITS;

terminal DIGITS returns PositiveIntegerLiteral:		DIGIT+;

terminal fragment DIGIT: 						'0'..'9';
```

I've tried this for other values as well (e.g., single digit values such as `0` or `2`, also two digits with a space in between them, e.g., `1 2` (in case concatenated digits are not recognized as individual items)).

What may be problematic is the statement that `terminal DIGITS` returns `PositiveIntegerLiteral` -
 recommend removing the `returns PositiveIntegerLiteral` part. Since it worked before, another solution would be to change this part back to `INT`, unless there is a good reason not to. I realize that this change would allow negative values to be specified as well, but it would at least parse correctly.

**Comment by NicolasRouquette** [comment]
I managed to reproduce this problem in a unit test; making a fix...
