### ISSUE TITLE
Conversion of DecimalValue Fails During Serialization

### ISSUE THREAD

**Issue by sjiherzig** [JPL-IMCE/gov.nasa.jpl.imce.oml#91]
Serialization fails when attempting to serialize a model with a `DecimalValue`. The following example (written in Xtend) illustrates this:

```xtend
val unlimitedNatural = omlTerminologiesFactory.createNumericScalarRestriction()
unlimitedNatural.setName("UnlimitedNatural")
unlimitedNatural.setRestrictedRange(xsdInt)
    	
val literalNumber = omlCommonFactory.createLiteralDecimal
literalNumber.decimal = new DecimalValue("0")
    	    	
unlimitedNatural.setMinInclusive(literalNumber)
```

The above leads to the following error:

```
Exception in thread "main" java.lang.RuntimeException: Error while converting value 'gov.nasa.jpl.imce.oml.model.datatypes.DecimalValue@3c62be3c' for grammar rule 'DECIMAL' to string via ValueConverter.
Caused By: org.eclipse.xtext.conversion.ValueConverterException: The value 'gov.nasa.jpl.imce.oml.model.datatypes.DecimalValue@3c62be3c' is an invalid DECIMAL
Semantic Object: Extent.modules[0]->TerminologyGraph.boxStatements[0]->NumericScalarRestriction'UnlimitedNatural'.minInclusive->LiteralDecimal
```

Far fetched, but: the `DecimalValue` type currently uses a `String` value to represent the value of the decimal internally, while `DIGIT` in the grammar is a numeric digit - is this the issue, possibly?

**Comment by NicolasRouquette** [comment]
This kind of error usually suggests a misconfiguration in the value converter service.
In this case, it's in `/gov.nasa.jpl.imce.oml.dsl/src/gov/nasa/jpl/imce/oml/dsl/util/OMLValueConverterService.xtend`
